// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: iou/iou.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_lcnem_ioux_types "github.com/lcnem/ioux/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type IouNamespace struct {
	Id     string                                       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" yaml:"id"`
	Admin  github_com_lcnem_ioux_types.StringAccAddress `protobuf:"bytes,2,opt,name=admin,proto3,customtype=github.com/lcnem/ioux/types.StringAccAddress" json:"admin" yaml:"admin"`
	Issuer github_com_lcnem_ioux_types.StringAccAddress `protobuf:"bytes,3,opt,name=issuer,proto3,customtype=github.com/lcnem/ioux/types.StringAccAddress" json:"issuer" yaml:"issuer"`
}

func (m *IouNamespace) Reset()         { *m = IouNamespace{} }
func (m *IouNamespace) String() string { return proto.CompactTextString(m) }
func (*IouNamespace) ProtoMessage()    {}
func (*IouNamespace) Descriptor() ([]byte, []int) {
	return fileDescriptor_25ea6ba5d33a6536, []int{0}
}
func (m *IouNamespace) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IouNamespace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IouNamespace.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IouNamespace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IouNamespace.Merge(m, src)
}
func (m *IouNamespace) XXX_Size() int {
	return m.Size()
}
func (m *IouNamespace) XXX_DiscardUnknown() {
	xxx_messageInfo_IouNamespace.DiscardUnknown(m)
}

var xxx_messageInfo_IouNamespace proto.InternalMessageInfo

func (m *IouNamespace) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MsgCreateIouNamespace struct {
	Id     string                                       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" yaml:"id"`
	Admin  github_com_lcnem_ioux_types.StringAccAddress `protobuf:"bytes,2,opt,name=admin,proto3,customtype=github.com/lcnem/ioux/types.StringAccAddress" json:"admin" yaml:"admin"`
	Issuer github_com_lcnem_ioux_types.StringAccAddress `protobuf:"bytes,3,opt,name=issuer,proto3,customtype=github.com/lcnem/ioux/types.StringAccAddress" json:"issuer" yaml:"issuer"`
}

func (m *MsgCreateIouNamespace) Reset()         { *m = MsgCreateIouNamespace{} }
func (m *MsgCreateIouNamespace) String() string { return proto.CompactTextString(m) }
func (*MsgCreateIouNamespace) ProtoMessage()    {}
func (*MsgCreateIouNamespace) Descriptor() ([]byte, []int) {
	return fileDescriptor_25ea6ba5d33a6536, []int{1}
}
func (m *MsgCreateIouNamespace) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateIouNamespace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateIouNamespace.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateIouNamespace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateIouNamespace.Merge(m, src)
}
func (m *MsgCreateIouNamespace) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateIouNamespace) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateIouNamespace.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateIouNamespace proto.InternalMessageInfo

func (m *MsgCreateIouNamespace) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MsgUpdateIouNamespaceIssuer struct {
	Id     string                                       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" yaml:"id"`
	Admin  github_com_lcnem_ioux_types.StringAccAddress `protobuf:"bytes,2,opt,name=admin,proto3,customtype=github.com/lcnem/ioux/types.StringAccAddress" json:"admin" yaml:"admin"`
	Issuer github_com_lcnem_ioux_types.StringAccAddress `protobuf:"bytes,3,opt,name=issuer,proto3,customtype=github.com/lcnem/ioux/types.StringAccAddress" json:"issuer" yaml:"issuer"`
}

func (m *MsgUpdateIouNamespaceIssuer) Reset()         { *m = MsgUpdateIouNamespaceIssuer{} }
func (m *MsgUpdateIouNamespaceIssuer) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateIouNamespaceIssuer) ProtoMessage()    {}
func (*MsgUpdateIouNamespaceIssuer) Descriptor() ([]byte, []int) {
	return fileDescriptor_25ea6ba5d33a6536, []int{2}
}
func (m *MsgUpdateIouNamespaceIssuer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateIouNamespaceIssuer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateIouNamespaceIssuer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateIouNamespaceIssuer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateIouNamespaceIssuer.Merge(m, src)
}
func (m *MsgUpdateIouNamespaceIssuer) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateIouNamespaceIssuer) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateIouNamespaceIssuer.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateIouNamespaceIssuer proto.InternalMessageInfo

func (m *MsgUpdateIouNamespaceIssuer) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MsgUpdateIouNamespaceAdmin struct {
	Id          string                                       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" yaml:"id"`
	AdminBefore github_com_lcnem_ioux_types.StringAccAddress `protobuf:"bytes,2,opt,name=admin_before,json=adminBefore,proto3,customtype=github.com/lcnem/ioux/types.StringAccAddress" json:"admin_before" yaml:"admin_before"`
	AdminAfter  github_com_lcnem_ioux_types.StringAccAddress `protobuf:"bytes,3,opt,name=admin_after,json=adminAfter,proto3,customtype=github.com/lcnem/ioux/types.StringAccAddress" json:"admin_after" yaml:"admin_after"`
}

func (m *MsgUpdateIouNamespaceAdmin) Reset()         { *m = MsgUpdateIouNamespaceAdmin{} }
func (m *MsgUpdateIouNamespaceAdmin) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateIouNamespaceAdmin) ProtoMessage()    {}
func (*MsgUpdateIouNamespaceAdmin) Descriptor() ([]byte, []int) {
	return fileDescriptor_25ea6ba5d33a6536, []int{3}
}
func (m *MsgUpdateIouNamespaceAdmin) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateIouNamespaceAdmin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateIouNamespaceAdmin.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateIouNamespaceAdmin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateIouNamespaceAdmin.Merge(m, src)
}
func (m *MsgUpdateIouNamespaceAdmin) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateIouNamespaceAdmin) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateIouNamespaceAdmin.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateIouNamespaceAdmin proto.InternalMessageInfo

func (m *MsgUpdateIouNamespaceAdmin) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MsgIssueIou struct {
	NamespaceId string                                       `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty" yaml:"namespace_id"`
	Prefix      string                                       `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty" yaml:"prefix"`
	BaseDenom   string                                       `protobuf:"bytes,3,opt,name=base_denom,json=baseDenom,proto3" json:"base_denom,omitempty" yaml:"base_denom"`
	Issuer      github_com_lcnem_ioux_types.StringAccAddress `protobuf:"bytes,4,opt,name=issuer,proto3,customtype=github.com/lcnem/ioux/types.StringAccAddress" json:"issuer" yaml:"issuer"`
	Destination github_com_lcnem_ioux_types.StringAccAddress `protobuf:"bytes,5,opt,name=destination,proto3,customtype=github.com/lcnem/ioux/types.StringAccAddress" json:"destination" yaml:"destination"`
	Amount      github_com_cosmos_cosmos_sdk_types.Int       `protobuf:"bytes,6,opt,name=amount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"amount" yaml:"amount"`
}

func (m *MsgIssueIou) Reset()         { *m = MsgIssueIou{} }
func (m *MsgIssueIou) String() string { return proto.CompactTextString(m) }
func (*MsgIssueIou) ProtoMessage()    {}
func (*MsgIssueIou) Descriptor() ([]byte, []int) {
	return fileDescriptor_25ea6ba5d33a6536, []int{4}
}
func (m *MsgIssueIou) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgIssueIou) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgIssueIou.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgIssueIou) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgIssueIou.Merge(m, src)
}
func (m *MsgIssueIou) XXX_Size() int {
	return m.Size()
}
func (m *MsgIssueIou) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgIssueIou.DiscardUnknown(m)
}

var xxx_messageInfo_MsgIssueIou proto.InternalMessageInfo

func (m *MsgIssueIou) GetNamespaceId() string {
	if m != nil {
		return m.NamespaceId
	}
	return ""
}

func (m *MsgIssueIou) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *MsgIssueIou) GetBaseDenom() string {
	if m != nil {
		return m.BaseDenom
	}
	return ""
}

type MsgBurnIou struct {
	NamespaceId string                                       `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty" yaml:"namespace_id"`
	Prefix      string                                       `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty" yaml:"prefix"`
	BaseDenom   string                                       `protobuf:"bytes,3,opt,name=base_denom,json=baseDenom,proto3" json:"base_denom,omitempty" yaml:"base_denom"`
	Holder      github_com_lcnem_ioux_types.StringAccAddress `protobuf:"bytes,4,opt,name=holder,proto3,customtype=github.com/lcnem/ioux/types.StringAccAddress" json:"holder" yaml:"holder"`
	Amount      github_com_cosmos_cosmos_sdk_types.Int       `protobuf:"bytes,5,opt,name=amount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"amount" yaml:"amount"`
}

func (m *MsgBurnIou) Reset()         { *m = MsgBurnIou{} }
func (m *MsgBurnIou) String() string { return proto.CompactTextString(m) }
func (*MsgBurnIou) ProtoMessage()    {}
func (*MsgBurnIou) Descriptor() ([]byte, []int) {
	return fileDescriptor_25ea6ba5d33a6536, []int{5}
}
func (m *MsgBurnIou) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBurnIou) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBurnIou.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBurnIou) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBurnIou.Merge(m, src)
}
func (m *MsgBurnIou) XXX_Size() int {
	return m.Size()
}
func (m *MsgBurnIou) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBurnIou.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBurnIou proto.InternalMessageInfo

func (m *MsgBurnIou) GetNamespaceId() string {
	if m != nil {
		return m.NamespaceId
	}
	return ""
}

func (m *MsgBurnIou) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *MsgBurnIou) GetBaseDenom() string {
	if m != nil {
		return m.BaseDenom
	}
	return ""
}

type Params struct {
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_25ea6ba5d33a6536, []int{6}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func init() {
	proto.RegisterType((*IouNamespace)(nil), "ioux.iou.IouNamespace")
	proto.RegisterType((*MsgCreateIouNamespace)(nil), "ioux.iou.MsgCreateIouNamespace")
	proto.RegisterType((*MsgUpdateIouNamespaceIssuer)(nil), "ioux.iou.MsgUpdateIouNamespaceIssuer")
	proto.RegisterType((*MsgUpdateIouNamespaceAdmin)(nil), "ioux.iou.MsgUpdateIouNamespaceAdmin")
	proto.RegisterType((*MsgIssueIou)(nil), "ioux.iou.MsgIssueIou")
	proto.RegisterType((*MsgBurnIou)(nil), "ioux.iou.MsgBurnIou")
	proto.RegisterType((*Params)(nil), "ioux.iou.Params")
}

func init() { proto.RegisterFile("iou/iou.proto", fileDescriptor_25ea6ba5d33a6536) }

var fileDescriptor_25ea6ba5d33a6536 = []byte{
	// 594 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x95, 0x41, 0x8b, 0xd3, 0x4e,
	0x18, 0xc6, 0x9b, 0xee, 0x7f, 0xc3, 0xee, 0xb4, 0x3d, 0x6c, 0xfe, 0x2e, 0x96, 0x8a, 0x89, 0xce,
	0x41, 0x14, 0xb4, 0x61, 0xd1, 0xd3, 0x7a, 0x90, 0xd6, 0xf5, 0x50, 0xa5, 0x22, 0x11, 0x11, 0x16,
	0xa4, 0x4c, 0x32, 0xd3, 0xec, 0xb0, 0xcd, 0x4c, 0xc8, 0xcc, 0x48, 0xf7, 0x5b, 0x78, 0xf4, 0x23,
	0xed, 0xb1, 0x47, 0xf1, 0x50, 0xb4, 0xbd, 0x78, 0xb5, 0x17, 0xaf, 0x92, 0xc9, 0x6c, 0x1b, 0x96,
	0x05, 0xa1, 0xd4, 0x83, 0x7a, 0x4a, 0x9e, 0xbc, 0x2f, 0xbf, 0x67, 0x9e, 0x77, 0x86, 0x09, 0x68,
	0x50, 0xae, 0x7c, 0xca, 0x55, 0x3b, 0xcd, 0xb8, 0xe4, 0xce, 0x0e, 0xe5, 0x6a, 0xdc, 0xa6, 0x5c,
	0xb5, 0xae, 0xc5, 0x3c, 0xe6, 0xfa, 0xa3, 0x9f, 0xbf, 0x15, 0xf5, 0x96, 0x17, 0x73, 0x1e, 0x8f,
	0x88, 0xaf, 0x55, 0xa8, 0x86, 0xbe, 0xa4, 0x09, 0x11, 0x12, 0x25, 0xa9, 0x69, 0x70, 0x2f, 0x37,
	0x60, 0x95, 0x21, 0x49, 0x39, 0xbb, 0xa8, 0x47, 0x5c, 0x24, 0x5c, 0xf8, 0x21, 0x12, 0xc4, 0x7f,
	0x7f, 0x10, 0x12, 0x89, 0x0e, 0xfc, 0x88, 0x53, 0x53, 0x87, 0xdf, 0x2c, 0x50, 0xef, 0x71, 0xf5,
	0x12, 0x25, 0x44, 0xa4, 0x28, 0x22, 0xce, 0x4d, 0x50, 0xa5, 0xb8, 0x69, 0xdd, 0xb2, 0xee, 0xee,
	0x76, 0x1b, 0x8b, 0xa9, 0xb7, 0x7b, 0x86, 0x92, 0xd1, 0x21, 0xa4, 0x18, 0x06, 0x55, 0x8a, 0x9d,
	0x63, 0xb0, 0x8d, 0x70, 0x42, 0x59, 0xb3, 0xaa, 0x3b, 0x8e, 0xce, 0xa7, 0x5e, 0xe5, 0xf3, 0xd4,
	0xbb, 0x1f, 0x53, 0x79, 0xa2, 0xc2, 0x76, 0xc4, 0x13, 0x7f, 0x14, 0x31, 0x92, 0xe4, 0x19, 0xc7,
	0xbe, 0x3c, 0x4b, 0x89, 0x68, 0xbf, 0x96, 0x19, 0x65, 0x71, 0x27, 0x8a, 0x3a, 0x18, 0x67, 0x44,
	0x88, 0xc5, 0xd4, 0xab, 0x17, 0x54, 0x8d, 0x82, 0x41, 0x81, 0x74, 0xde, 0x01, 0x9b, 0x0a, 0xa1,
	0x48, 0xd6, 0xdc, 0xd2, 0xf0, 0x67, 0x6b, 0xc2, 0x1b, 0x66, 0xc9, 0x9a, 0x05, 0x03, 0x03, 0x85,
	0xdf, 0x2d, 0xb0, 0xdf, 0x17, 0xf1, 0xd3, 0x8c, 0x20, 0x49, 0xfe, 0x91, 0xcc, 0x3f, 0x2c, 0x70,
	0xa3, 0x2f, 0xe2, 0x37, 0x29, 0xbe, 0x94, 0xb9, 0xa7, 0xeb, 0x7f, 0x71, 0xf2, 0x8f, 0x55, 0xd0,
	0xba, 0x32, 0x79, 0x47, 0xbb, 0xff, 0x22, 0x38, 0x03, 0x75, 0xbd, 0xca, 0x41, 0x48, 0x86, 0x3c,
	0x23, 0x26, 0xff, 0x8b, 0x35, 0x97, 0xf8, 0x7f, 0x29, 0xbf, 0x21, 0xc2, 0xa0, 0xa6, 0x65, 0x57,
	0x2b, 0xe7, 0x14, 0x14, 0x72, 0x80, 0x86, 0x72, 0x39, 0x91, 0xe7, 0x6b, 0xda, 0x39, 0x65, 0x3b,
	0x0d, 0x84, 0x01, 0xd0, 0xaa, 0xa3, 0xc5, 0x64, 0x0b, 0xd4, 0xfa, 0x22, 0xd6, 0x47, 0xa0, 0xc7,
	0x95, 0x73, 0x08, 0xea, 0xec, 0x62, 0x3a, 0x83, 0xe5, 0x54, 0xae, 0xaf, 0x16, 0x5e, 0xae, 0xc2,
	0xa0, 0xb6, 0x94, 0x3d, 0xec, 0xdc, 0x03, 0x76, 0x9a, 0x91, 0x21, 0x1d, 0x9b, 0x11, 0xed, 0xad,
	0x76, 0xa4, 0xf8, 0x0e, 0x03, 0xd3, 0xe0, 0x3c, 0x02, 0x20, 0xbf, 0x85, 0x06, 0x98, 0x30, 0x9e,
	0x98, 0x88, 0xfb, 0x8b, 0xa9, 0xb7, 0x57, 0xb4, 0xaf, 0x6a, 0x30, 0xd8, 0xcd, 0xc5, 0x51, 0xfe,
	0x5e, 0x3a, 0x26, 0xff, 0xfd, 0x86, 0x63, 0xe2, 0x8c, 0x40, 0x0d, 0x13, 0x21, 0x29, 0xd3, 0x97,
	0x66, 0x73, 0x7b, 0x13, 0x83, 0x2f, 0x01, 0x61, 0x50, 0xc6, 0x3b, 0x6f, 0x81, 0x8d, 0x12, 0xae,
	0x98, 0x6c, 0xda, 0xda, 0xe8, 0x89, 0x31, 0xba, 0x53, 0x32, 0x32, 0x17, 0x76, 0xf1, 0x78, 0x20,
	0xf0, 0xa9, 0xf1, 0xeb, 0x31, 0xb9, 0x8a, 0x51, 0x50, 0x60, 0x60, 0x70, 0xf0, 0x6b, 0x15, 0x80,
	0xbe, 0x88, 0xbb, 0x2a, 0x63, 0x7f, 0xc2, 0x8e, 0x9e, 0xf0, 0x11, 0xde, 0xd4, 0x8e, 0x16, 0x2c,
	0x18, 0x18, 0x68, 0x69, 0xc6, 0xdb, 0x9b, 0x9d, 0xf1, 0x0e, 0xb0, 0x5f, 0xa1, 0x0c, 0x25, 0xa2,
	0xfb, 0xf8, 0x7c, 0xe6, 0x5a, 0x93, 0x99, 0x6b, 0x7d, 0x99, 0xb9, 0xd6, 0x87, 0xb9, 0x5b, 0x99,
	0xcc, 0xdd, 0xca, 0xa7, 0xb9, 0x5b, 0x39, 0xbe, 0x7d, 0x75, 0x86, 0x71, 0xfe, 0x28, 0x3c, 0x42,
	0x5b, 0xff, 0x78, 0x1f, 0xfe, 0x0c, 0x00, 0x00, 0xff, 0xff, 0xe9, 0xd8, 0x5a, 0xb1, 0x0a, 0x08,
	0x00, 0x00,
}

func (m *IouNamespace) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IouNamespace) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IouNamespace) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Issuer.Size()
		i -= size
		if _, err := m.Issuer.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintIou(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.Admin.Size()
		i -= size
		if _, err := m.Admin.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintIou(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintIou(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateIouNamespace) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateIouNamespace) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateIouNamespace) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Issuer.Size()
		i -= size
		if _, err := m.Issuer.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintIou(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.Admin.Size()
		i -= size
		if _, err := m.Admin.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintIou(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintIou(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateIouNamespaceIssuer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateIouNamespaceIssuer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateIouNamespaceIssuer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Issuer.Size()
		i -= size
		if _, err := m.Issuer.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintIou(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.Admin.Size()
		i -= size
		if _, err := m.Admin.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintIou(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintIou(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateIouNamespaceAdmin) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateIouNamespaceAdmin) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateIouNamespaceAdmin) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.AdminAfter.Size()
		i -= size
		if _, err := m.AdminAfter.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintIou(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.AdminBefore.Size()
		i -= size
		if _, err := m.AdminBefore.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintIou(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintIou(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgIssueIou) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgIssueIou) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgIssueIou) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintIou(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.Destination.Size()
		i -= size
		if _, err := m.Destination.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintIou(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.Issuer.Size()
		i -= size
		if _, err := m.Issuer.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintIou(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.BaseDenom) > 0 {
		i -= len(m.BaseDenom)
		copy(dAtA[i:], m.BaseDenom)
		i = encodeVarintIou(dAtA, i, uint64(len(m.BaseDenom)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Prefix) > 0 {
		i -= len(m.Prefix)
		copy(dAtA[i:], m.Prefix)
		i = encodeVarintIou(dAtA, i, uint64(len(m.Prefix)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.NamespaceId) > 0 {
		i -= len(m.NamespaceId)
		copy(dAtA[i:], m.NamespaceId)
		i = encodeVarintIou(dAtA, i, uint64(len(m.NamespaceId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgBurnIou) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBurnIou) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBurnIou) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintIou(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.Holder.Size()
		i -= size
		if _, err := m.Holder.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintIou(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.BaseDenom) > 0 {
		i -= len(m.BaseDenom)
		copy(dAtA[i:], m.BaseDenom)
		i = encodeVarintIou(dAtA, i, uint64(len(m.BaseDenom)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Prefix) > 0 {
		i -= len(m.Prefix)
		copy(dAtA[i:], m.Prefix)
		i = encodeVarintIou(dAtA, i, uint64(len(m.Prefix)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.NamespaceId) > 0 {
		i -= len(m.NamespaceId)
		copy(dAtA[i:], m.NamespaceId)
		i = encodeVarintIou(dAtA, i, uint64(len(m.NamespaceId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintIou(dAtA []byte, offset int, v uint64) int {
	offset -= sovIou(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *IouNamespace) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovIou(uint64(l))
	}
	l = m.Admin.Size()
	n += 1 + l + sovIou(uint64(l))
	l = m.Issuer.Size()
	n += 1 + l + sovIou(uint64(l))
	return n
}

func (m *MsgCreateIouNamespace) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovIou(uint64(l))
	}
	l = m.Admin.Size()
	n += 1 + l + sovIou(uint64(l))
	l = m.Issuer.Size()
	n += 1 + l + sovIou(uint64(l))
	return n
}

func (m *MsgUpdateIouNamespaceIssuer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovIou(uint64(l))
	}
	l = m.Admin.Size()
	n += 1 + l + sovIou(uint64(l))
	l = m.Issuer.Size()
	n += 1 + l + sovIou(uint64(l))
	return n
}

func (m *MsgUpdateIouNamespaceAdmin) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovIou(uint64(l))
	}
	l = m.AdminBefore.Size()
	n += 1 + l + sovIou(uint64(l))
	l = m.AdminAfter.Size()
	n += 1 + l + sovIou(uint64(l))
	return n
}

func (m *MsgIssueIou) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.NamespaceId)
	if l > 0 {
		n += 1 + l + sovIou(uint64(l))
	}
	l = len(m.Prefix)
	if l > 0 {
		n += 1 + l + sovIou(uint64(l))
	}
	l = len(m.BaseDenom)
	if l > 0 {
		n += 1 + l + sovIou(uint64(l))
	}
	l = m.Issuer.Size()
	n += 1 + l + sovIou(uint64(l))
	l = m.Destination.Size()
	n += 1 + l + sovIou(uint64(l))
	l = m.Amount.Size()
	n += 1 + l + sovIou(uint64(l))
	return n
}

func (m *MsgBurnIou) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.NamespaceId)
	if l > 0 {
		n += 1 + l + sovIou(uint64(l))
	}
	l = len(m.Prefix)
	if l > 0 {
		n += 1 + l + sovIou(uint64(l))
	}
	l = len(m.BaseDenom)
	if l > 0 {
		n += 1 + l + sovIou(uint64(l))
	}
	l = m.Holder.Size()
	n += 1 + l + sovIou(uint64(l))
	l = m.Amount.Size()
	n += 1 + l + sovIou(uint64(l))
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovIou(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozIou(x uint64) (n int) {
	return sovIou(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *IouNamespace) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIou
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IouNamespace: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IouNamespace: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIou
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIou
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIou
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Admin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIou
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIou
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIou
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Admin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Issuer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIou
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIou
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIou
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Issuer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIou(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIou
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateIouNamespace) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIou
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateIouNamespace: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateIouNamespace: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIou
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIou
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIou
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Admin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIou
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIou
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIou
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Admin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Issuer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIou
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIou
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIou
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Issuer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIou(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIou
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateIouNamespaceIssuer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIou
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateIouNamespaceIssuer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateIouNamespaceIssuer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIou
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIou
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIou
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Admin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIou
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIou
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIou
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Admin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Issuer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIou
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIou
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIou
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Issuer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIou(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIou
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateIouNamespaceAdmin) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIou
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateIouNamespaceAdmin: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateIouNamespaceAdmin: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIou
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIou
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIou
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AdminBefore", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIou
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIou
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIou
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AdminBefore.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AdminAfter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIou
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIou
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIou
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AdminAfter.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIou(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIou
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgIssueIou) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIou
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgIssueIou: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgIssueIou: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NamespaceId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIou
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIou
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIou
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NamespaceId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Prefix", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIou
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIou
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIou
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Prefix = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIou
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIou
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIou
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BaseDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Issuer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIou
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIou
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIou
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Issuer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Destination", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIou
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIou
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIou
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Destination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIou
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIou
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIou
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIou(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIou
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBurnIou) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIou
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBurnIou: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBurnIou: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NamespaceId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIou
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIou
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIou
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NamespaceId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Prefix", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIou
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIou
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIou
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Prefix = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIou
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIou
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIou
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BaseDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Holder", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIou
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIou
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIou
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Holder.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIou
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIou
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIou
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIou(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIou
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIou
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipIou(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIou
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipIou(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowIou
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIou
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIou
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthIou
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupIou
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthIou
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthIou        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowIou          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupIou = fmt.Errorf("proto: unexpected end of group")
)
